@admin-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NjgyODQ5NzR9.hgTWiTEmfVDqWPsSPgj77q3zmmbwrg-3K7WHQEFmEcM
@jwt-2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjgyODQ4Mzl9.LkQl0n7QuY4JBx41EnOSXh3rF9lz-FmawSPa_hxDmjA

### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS SHOW
GET http://localhost:3000/products/6.json

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt-2}}
Content-Type: application/json

{
"name": "Chocolate cake",
"price": 22,
"image_url": "no url", 
"description": "hi",
"created_at": "today",
"supplier_id": "2"
}

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/6.json
Authorization: Bearer {{admin-jwt}}
Content-Type: application/json

{
  "name": "Itsy bitsy Hippo"
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/20.json
Authorization: Bearer {{admin-jwt}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "sara",
  "email": "sara@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "sara@example.com",
  "password": "password"
}


### ORDERS CREATE
POST http://localhost:3000/orders.json
Authorization: Bearer 
Content-Type: application/json

{
"product_id": 6,
"quantity": 5
}


### ORDERS SHOW
GET http://localhost:3000/orders/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjgyNzU5OTV9.xPmt-2uY2U23xTaD2_Y0fTZhvU_U-yhXnaKEMwrnRXg
Content-Type: application/json



### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjgyNzU5OTV9.xPmt-2uY2U23xTaD2_Y0fTZhvU_U-yhXnaKEMwrnRXg
Content-Type: application/json

