@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NzE4MTYxODF9.Q8iw54OUU8vUtUeqAMMCEyjzteH35nTjvwL3eGK_UD8


### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS SHOW
GET http://localhost:3000/products/6.json

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"name": "FROZEN CAKE",
"price": 16,
"image_url": "no url", 
"description": "BRRR",
"created_at": "today",
"supplier_id": "2"
}

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/21.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "price": -16
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/21.json
Authorization: Bearer {{jwt}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "sara@example.com",
  "password": "password"
}


### ORDERS CREATE
POST http://localhost:3000/orders.json
Authorization: Bearer 
Content-Type: application/json

{
"product_id": 6,
"quantity": 5
}


### ORDERS SHOW
GET http://localhost:3000/orders/2.json
Authorization: Bearer 
Content-Type: application/json



### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer 
Content-Type: application/json


### CARTED_PRODUCTS CREATE
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"product_id": 1,
"quantity": 4,
"order_id": "nil"
}


### CARTED_PRODUCTS INDEX
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json



